### ISSUE TITLE
XSS vulnerabilities

### ISSUE THREAD

**Issue by unuseless** [Dunks1980/bay.js#1]
Hi,
First, thanks for the project!
After testing the live playground and the first reactive example, I believe the code is susceptible to XSS attacks.
If you start entering '<' in the input box, this will be interpreted as html.

Is there some built in way to escape strings/variables?

**Comment by Dunks1980** [comment]
Hi,
Thanks, I will see if I can add some escaping/sanitising on user strings/variables, currently the suggested CSP prevents inline scripts from executing so I may need to add some instructions much like Vue https://vuejs.org/guide/best-practices/security.html#what-vue-does-to-protect-you

**Comment by unuseless** [comment]
I think escaping should be the default.  Maybe you could take inspiration from  https://github.com/cferdinandi/reef or https://github.com/developit/htm which escape strings when variables are interpolated with `${ }`.
Also attribute bindings as described in the referenced Vue docs are a problem.
Thanks for the fast uptake!

**Comment by Dunks1980** [comment]
I have added some basic sanitation on user strings/input for now, I will checkout you suggestions when I have a deeper dive, many thanks

**Comment by Dunks1980** [comment]
I have added some basic sanitation on user strings/input for now, I will checkout you suggestions when I have a deeper dive, many thanks.

**Comment by Dunks1980** [comment]
entering '<' no longer possible.
