### ISSUE TITLE
I just want to say thank you!

### ISSUE THREAD

**Issue by bubnenkoff** [Dunks1980/bay.js#12]
Thank you for your work. I'm really really tired of heavy JS frameworks from which I only need 5% functionality.
I searched for a long time in the search engine for libraries for my small site. In the end your library is the best I found.
Why am I writing this -- I just want to say thank you! Don't believe those who say "your library solves nothing". It does. It does. There's a kargo cult in IT right now. And people don't see simple solutions to complex problems! 

This topic can be closed! I only wish the library was as nodejs-free as possible. I want to have great old websites

**Comment by Dunks1980** [comment]
Many thanks for your praise, I will continue to update and add new functionality where and when I can.

**Comment by Dunks1980** [comment]
Closeed
