### ISSUE TITLE
Logo effect

### ISSUE THREAD

**Issue by jgentes** [Dunks1980/bay.js#2]
How'd you get that logo effect on the bay.js homepage? Is that something you can share? Very cool! :)

**Comment by Dunks1980** [comment]
Hi thanks, the source code can be found by putting this in address bar:
view-source:https://bayjs.org/component_imports/logo.html
the SVG could be switched out with something else,
please can I ask where you came across bay.js?

**Comment by jgentes** [comment]
Nice, thanks!

I saw it in a newsletter: https://frontendfoc.us/issues/575
